---
jobs:
  final:
    docker:
      - image: bash:latest
    steps:
      - run:
          name: Finish cooking
          command: echo "Finished cooking"
lint_and_unit: &lint_and_unit
  - delivery
  - danger
  - lint-yaml
  - lint-markdown
version: 2.1
orbs:
  kitchen: sous-chefs/kitchen@2
workflows:
  kitchen:
    jobs:
      - kitchen/yamllint:
          name: lint-yaml
      - kitchen/mdlint:
          name: lint-markdown
      - kitchen/danger:
          name: danger
          context: Danger
      - kitchen/delivery:
          name: delivery
      - kitchen/dokken-single:
          name: proxy
          suite: proxy
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: default-debian-8
          suite: default-debian-8
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: default-debian-9
          suite: default-debian-9
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: default-centos-6
          suite: default-centos-6
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: default-centos-7
          suite: default-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: default-ubuntu-1604
          suite: default-ubuntu-1604
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: default-ubuntu-1804
          suite: default-ubuntu-1804
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: default-amazonlinux
          suite: default-amazonlinux
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: ldap-debian-8
          suite: ldap-debian-8
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: ldap-debian-9
          suite: ldap-debian-9
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: ldap-centos-6
          suite: ldap-centos-6
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: ldap-centos-7
          suite: ldap-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: ldap-ubuntu-1604
          suite: ldap-ubuntu-1604
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: ldap-ubuntu-1804
          suite: ldap-ubuntu-1804
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: ldap-amazonlinux
          suite: ldap-amazonlinux
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: plugins-debian-8
          suite: plugins-debian-8
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: plugins-debian-9
          suite: plugins-debian-9
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: plugins-centos-6
          suite: plugins-centos-6
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: plugins-centos-7
          suite: plugins-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: plugins-ubuntu-1604
          suite: plugins-ubuntu-1604
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: plugins-ubuntu-1804
          suite: plugins-ubuntu-1804
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: plugins-amazonlinux
          suite: plugins-amazonlinux
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: basic-debian-8
          suite: basic-debian-8
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: basic-debian-9
          suite: basic-debian-9
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: basic-centos-6
          suite: basic-centos-6
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: basic-centos-7
          suite: basic-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: basic-ubuntu-1604
          suite: basic-ubuntu-1604
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: basic-ubuntu-1804
          suite: basic-ubuntu-1804
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: basic-amazonlinux
          suite: basic-amazonlinux
          requires: *lint_and_unit
      - final:
          requires:
            - default-debian-8
            - default-debian-9
            - default-centos-6
            - default-centos-7
            - default-ubuntu-1604
            - default-ubuntu-1804
            - default-amazonlinux
            - ldap-debian-8
            - ldap-debian-9
            - ldap-centos-6
            - ldap-centos-7
            - ldap-ubuntu-1604
            - ldap-ubuntu-1804
            - ldap-amazonlinux
            - plugins-debian-8
            - plugins-debian-9
            - plugins-centos-6
            - plugins-centos-7
            - plugins-ubuntu-1604
            - plugins-ubuntu-1804
            - plugins-amazonlinux
            - basic-debian-8
            - basic-debian-9
            - basic-centos-6
            - basic-centos-7
            - basic-ubuntu-1604
            - basic-ubuntu-1804
            - basic-amazonlinux
