version: 2.1

orbs:
  kitchen: sous-chefs/kitchen@1.0.0

workflows:
  kitchen:
    jobs:
      - kitchen/danger:
          name: danger
          context: Danger
      - kitchen/lint:
          name: lint
      - kitchen/dokken-single:
          name: centos-6
          platform: centos-6
          suite: default
          requires: [ lint, danger ]
      - kitchen/dokken-single:
          name: centos-7
          platform: centos-7
          suite: default
          requires: [ lint, danger ]
      - kitchen/dokken-single:
          name: debian-8
          platform: debian-8
          suite: default
          requires: [ lint, danger ]
      - kitchen/dokken-single:
          name: ubuntu-16.04
          platform: ubuntu-1604
          suite: default
          requires: [ lint, danger ]
